# Generated by Django 6.0 on 2026-01-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Картинка')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('full_text', models.TextField(verbose_name='Полная статья')),
                ('date_out', models.DateField(verbose_name='Дата выхода')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
