# Generated by Django 6.0 on 2026-01-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
