# Generated by Django 6.0 on 2026-01-15 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_out',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время'),
        ),
    ]
