# Generated by Django 6.0 on 2026-01-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
