# Generated by Django 6.0 on 2026-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_anime_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='published',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
