# Generated by Django 6.0 on 2026-01-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_anime_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
