# Generated by Django 6.0 on 2026-01-15 08:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_anime_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date_out',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выхода'),
        ),
    ]
